version: "3"
services:
  app:
    container_name: vila-task-reminder
    build: .
    depends_on:
      - mysql
    ports:
      - "8000:80"
      - "4433:443"
    volumes:
      - .:/var/www/html
    links:
      - mysql:mysql
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      JWT_SECRET: ${JWT_SECRET}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}

      DB_HOST: mysql
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SESSION_DRIVER: file
      CACHE_DRIVER: file
      QUEUE_DRIVER: sync

      CONTAINER_ROLE: ${CONTAINER_ROLE}
    restart: unless-stopped
  mysql:
    image: mysql:5.6
    container_name: vila-task-reminder-mysql
    ports:
      - "33067:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
  scheduler:
    container_name: vila-task-reminder-scheduler
    build: .
    depends_on:
      - mysql
      - app
    volumes:
      - .:/var/www/html
    links:
      - mysql:mysql
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      JWT_SECRET: ${JWT_SECRET}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}

      DB_HOST: mysql
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SESSION_DRIVER: file
      CACHE_DRIVER: file
      QUEUE_DRIVER: sync

      CONTAINER_ROLE: scheduler
    restart: unless-stopped
